export interface AssetItem {
	id: string;
	title: string;
	status:
		| "ongoing"
		| "approved"
		| "pending approval"
		| "denied"
		| "repaid"
		| "cancelled";
	reference: string;
	amount: string;
	progress?: number;
	date: string;
	description?: string;
	navigate?: (screen: string) => void;
}

export const assetList: AssetItem[] = [
	{
		id: "1",
		title: "Provisions",
		status: "ongoing",
		reference: "#2329230347",
		amount: "N20,000",
		progress: 20,
		date: "18 Sep",
		description: "Monthly provisions package",
	},
	{
		id: "2",
		title: "School Fees",
		status: "approved",
		reference: "#2329230348",
		amount: "N150,000",
		date: "15 Sep",
		description: "First semester school fees",
	},
	{
		id: "3",
		title: "Medical Bills",
		status: "pending approval",
		reference: "#2329230349",
		amount: "N45,000",
		date: "20 Sep",
		description: "Emergency medical treatment",
	},
	{
		id: "4",
		title: "Business Capital",
		status: "denied",
		reference: "#2329230350",
		amount: "N500,000",
		date: "12 Sep",
		description: "Small business startup capital",
	},
	{
		id: "5",
		title: "Home Renovation",
		status: "repaid",
		reference: "#2329230351",
		amount: "N300,000",
		date: "10 Sep",
		description: "Kitchen and bathroom renovation",
	},
	{
		id: "6",
		title: "Vehicle Purchase",
		status: "cancelled",
		reference: "#2329230352",
		amount: "N2,500,000",
		date: "08 Sep",
		description: "Used car purchase",
	},
	{
		id: "7",
		title: "Wedding Expenses",
		status: "ongoing",
		reference: "#2329230353",
		amount: "N800,000",
		progress: 60,
		date: "25 Sep",
		description: "Wedding ceremony and reception",
	},
	{
		id: "8",
		title: "Farm Equipment",
		status: "approved",
		reference: "#2329230354",
		amount: "N180,000",
		date: "22 Sep",
		description: "Tractor and farming tools",
	},
	{
		id: "9",
		title: "Emergency Fund",
		status: "pending approval",
		reference: "#2329230355",
		amount: "N100,000",
		date: "28 Sep",
		description: "Family emergency fund",
	},
	{
		id: "10",
		title: "Education Loan",
		status: "denied",
		reference: "#2329230356",
		amount: "N400,000",
		date: "05 Sep",
		description: "University tuition fees",
	},
	{
		id: "11",
		title: "Property Investment",
		status: "repaid",
		reference: "#2329230357",
		amount: "N1,200,000",
		date: "03 Sep",
		description: "Land purchase for investment",
	},
	{
		id: "12",
		title: "Technology Upgrade",
		status: "cancelled",
		reference: "#2329230358",
		amount: "N75,000",
		date: "01 Sep",
		description: "Computer and software upgrade",
	},
	{
		id: "13",
		title: "Healthcare Package",
		status: "ongoing",
		reference: "#2329230359",
		amount: "N120,000",
		progress: 40,
		date: "30 Sep",
		description: "Annual health insurance premium",
	},
	{
		id: "14",
		title: "Business Expansion",
		status: "approved",
		reference: "#2329230360",
		amount: "N750,000",
		date: "27 Sep",
		description: "Shop expansion and inventory",
	},
	{
		id: "15",
		title: "Family Support",
		status: "pending approval",
		reference: "#2329230361",
		amount: "N50,000",
		date: "24 Sep",
		description: "Support for extended family",
	},
	{
		id: "16",
		title: "Travel Expenses",
		status: "denied",
		reference: "#2329230362",
		amount: "N200,000",
		date: "19 Sep",
		description: "International business trip",
	},
	{
		id: "17",
		title: "Debt Consolidation",
		status: "repaid",
		reference: "#2329230363",
		amount: "N600,000",
		date: "17 Sep",
		description: "Consolidate multiple debts",
	},
	{
		id: "18",
		title: "Equipment Purchase",
		status: "cancelled",
		reference: "#2329230364",
		amount: "N95,000",
		date: "14 Sep",
		description: "Office equipment and furniture",
	},
	{
		id: "19",
		title: "Child Education",
		status: "ongoing",
		reference: "#2329230365",
		amount: "N250,000",
		progress: 80,
		date: "11 Sep",
		description: "Private school tuition fees",
	},
	{
		id: "20",
		title: "Agricultural Loan",
		status: "approved",
		reference: "#2329230366",
		amount: "N350,000",
		date: "07 Sep",
		description: "Crop farming and irrigation",
	},
	{
		id: "21",
		title: "Home Improvement",
		status: "pending approval",
		reference: "#2329230367",
		amount: "N180,000",
		date: "04 Sep",
		description: "Roof repair and painting",
	},
	{
		id: "22",
		title: "Transportation",
		status: "denied",
		reference: "#2329230368",
		amount: "N120,000",
		date: "02 Sep",
		description: "Motorcycle purchase for delivery",
	},
	{
		id: "23",
		title: "Investment Fund",
		status: "repaid",
		reference: "#2329230369",
		amount: "N900,000",
		date: "29 Aug",
		description: "Stock market investment",
	},
	{
		id: "24",
		title: "Event Planning",
		status: "cancelled",
		reference: "#2329230370",
		amount: "N65,000",
		date: "26 Aug",
		description: "Birthday party celebration",
	},
	{
		id: "25",
		title: "Technology Training",
		status: "ongoing",
		reference: "#2329230371",
		amount: "N85,000",
		progress: 30,
		date: "23 Aug",
		description: "Software development course",
	},
];
