const ScreenImages = {
	splashscreen: {
		splashscreen: require("./Splashscreen/splashscreen.png"),
	},
	Terminal: {
		background: require("./Terminal/background.png"),
	},
	profileScreen: {
		facebookIcon: require("./Profile/facebook.png"),
		twitterIcon: require("./Profile/twitter.png"),
		youtubeIcon: require("./Profile/YouTube.png"),
		mailLineIcon: require("./Profile/mail-line.png"),
		phoneLineIcon: require("./Profile/phone-line.png"),
		closeLineIcon: require("./Profile/close-line.png"),
		instaIcon: require("./Profile/insta.png"),
		linkedInIcon: require("./Profile/linkedin.png"),
	},
	SavingsScreen: {
		piggyVestImage: require("../screens/Savings/piggy-vest.png"),
		piggyImage: require("../screens/Savings/piggy.png"),
		purpleMoney: require("../screens/Savings/purple-money.png"),
		money: require("../screens/Savings/money.png"),
		hideIcon: require("../screens/Savings/eye-off-line.png"),
		showIcon: require("../screens/Savings/eye-line.png"),
		targetIcon: require("../screens/Savings/target.png"),
		calendarLine: require("../screens/Savings/calendar-line.png"),
		calendar: require("../screens/Savings/calendar.png"),
		bankIcon: require("../screens/Savings/bank-line.png"),
	},
	MoreScreen: {
		bankCard: require("../screens/More/bankcard.png"),
		piggybank: require("../screens/More/bankbuildingpiggybank.png"),
		tierOneIcon: require("../screens/More/tier1.png"),
		tierTwoIcon: require("../screens/More/tier2.png"),
		tierThreeIcon: require("../screens/More/tier3.png"),
		successTierTwoIcon: require("../screens/More/success-tier2.png"),
		successTierThreeIcon: require("../screens/More/success-tier3.png"),
		mapPinIcon: require("../screens/More/map-pin-line.png"),
		image: require("../screens/More/image.png"),
		phone: require("../screens/More/telephone.png"),
		paperMoney: require("../screens/More/paper-money.png"),
		arrowRightIcon: require("../screens/More/arrow-right-s-line.png"),
	},
	NewDeviceScreen: {
		phone: require("../screens/NewDevice/phone.png"),
	},
	kidashiReviewDetails: {
		userPlaceholder: require("../screens/Kidashi/OnboardingReviewDetails/vendor-image-placeholder.png"),
		editIcon: require("../screens/Kidashi/OnboardingReviewDetails/edit-icon.png"),
	},
	kidashiOnboardingStatus: {
		success: require("../screens/Kidashi/OnboardingStatus/check.png"),
		pending: require("../screens/Kidashi/OnboardingStatus/hourglass.png"),
		rejected: require("../screens/Kidashi/OnboardingStatus/error.png"),
		reregister: require("../screens/Kidashi/OnboardingStatus/reregister-icon.png"),
	},
	kidashiHome: {
		caretRight: require("./Kidashi/KidashiHome/caret-right-icon.png"),
		create: require("./Kidashi/KidashiHome/kidashi-plus-icon.png"),
		noTransactions: require("./Kidashi/KidashiHome/no-transactions.png"),
		noTrustCircles: require("./Kidashi/KidashiHome/no-trust-circles.png"),
		createAccount: require("./Kidashi/KidashiHome/create-account.png"),
		joinKidashi: require("./Kidashi/KidashiHome/members.png"),
		createTrustCircle: require("./Kidashi/KidashiHome/badge.png"),
		closeIcon: require("./Kidashi/KidashiHome/close.png"),
		loanDisbursement: require("./Kidashi/KidashiHome/loan-disbursement.png"),
		loanRepayment: require("./Kidashi/KidashiHome/loan-repayment.png"),
		searchIcon: require("./Kidashi/KidashiHome/search-icon.png"),
		trustCircleDetailsIcon: require("./Kidashi/KidashiHome/trust-circle-details-icon.png"),
		bellIcon: require("./Kidashi/KidashiHome/bell.png"),
		transferIcon: require("./Kidashi/KidashiHome/transfer-icon.png"),
		transferSuccessIcon: require("./Kidashi/KidashiHome/transfer-success-icon.png"),
		transactionDetailsHeaderIcon: require("./Kidashi/KidashiHome/transaction-details-header-icon.png"),
		transactionDetailsSuccessPill: require("./Kidashi/KidashiHome/transaction-details-success-pill.png"),
	},
	kidashiCreateTrustCircles: {
		headericon: require("./Kidashi/CreateTrustCircle/top-badge.png"),
		backIcon: require("./Kidashi/CreateTrustCircle/back-icon.png"),
		forwardIcon: require("./Kidashi/CreateTrustCircle/forward-icon.png"),
		lockIcon: require("./Kidashi/CreateTrustCircle/lock.png"),
		peopleIcon: require("./Kidashi/CreateTrustCircle/people.png"),
		buildIcon: require("./Kidashi/CreateTrustCircle/build.png"),
	},
	kidashiMemberDetails: {
		userPlaceholder: require("./Kidashi/MemberDetails/user.png"),
		transactionIcon: require("./Kidashi/MemberDetails/payment.png"),
		backIcon: require("./Kidashi/MemberDetails/back.png"),
		infoIcon: require("./Kidashi/MemberDetails/info.png"),
		chevronRightIcon: require("./Kidashi/MemberDetails/chevron-right.png"),
		arrowRightIcon: require("./Kidashi/MemberDetails/arrow-right.png"),
		debitIcon: require("./Kidashi/MemberDetails/debit.png"),
		creditIcon: require("./Kidashi/MemberDetails/credit.png"),
		debitCreditIcon: require("./Kidashi/MemberDetails/tran.png"),
		checkIcon: require("./Kidashi/MemberDetails/check.png"),
		downloadIcon: require("./Kidashi/MemberDetails/download.png"),
		searchIcon: require("./Kidashi/MemberDetails/search.png"),
		infoRedIcon: require("./Kidashi/MemberDetails/info-red.png"),
		packageIcon: require("./Kidashi/MemberDetails/package.png"),
		cautionIcon: require("./Kidashi/MemberDetails/caution.png"),
		boltIcon: require("./Kidashi/MemberDetails/bolt.png"),
		boxIcon: require("./Kidashi/MemberDetails/box.png"),
		closeIcon: require("./Kidashi/MemberDetails/close.png"),
		addCircleIcon: require("./Kidashi/MemberDetails/add-circle.png"),
		plusIcon: require("./Kidashi/MemberDetails/add-circle.png"),
		trashIcon: require("./Kidashi/MemberDetails/trash.png"),
		shieldIcon: require("./Kidashi/MemberDetails/shield.png"),
		resendIcon: require("./Kidashi/MemberDetails/resend.png"),
		successGif: require("./Kidashi/MemberDetails/success.gif"),
		verifiedIcon: require("./Kidashi/MemberDetails/verified.png"),
		addTeamIcon: require("./Kidashi/MemberDetails/add-team.png"),
	},
	kidashiMemberRegistration: {
		success: require("./Kidashi/MemberRegistration/success-icon.png"),
	},
	kidashiMemberAddition: {
		noticeIcon: require("./Kidashi/MemberAddition/notice-icon.png"),
		verifierTrustCircle: require("./Kidashi/MemberAddition/select-verifier-trust-circle.png"),
		addAnotherMemberIcon: require("./Kidashi/MemberAddition/add-circle.png"),
	},
};

export default ScreenImages;
